import NavBar from "@/components/navBar";
import { Provider } from "@/provider/apollo.provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "exprien",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <Provider>
        <body>{children}</body>
      </Provider>
    </html>
  );
}
